### ISSUE TITLE
Errors on starting the activity

### ISSUE THREAD

**Issue by yashagrawal3** [sugarlabs/finance-activity#12]
Terminal displays following errors on starting the activity: 
```    
1517838254.009602 ERROR root: filter options {0: 'Day', 1: 'Week', 2: 'Month', 3: 'Year', 4: 'Forever'}
1517837381.490595 WARNING root: icon_size is deprecated. Use pixel_size instead.
 ```

**Comment by yashagrawal3** [comment]
Many more errors and warning are displayed while using the activity.

**Comment by quozl** [comment]
In #13, @yashagrawal3 wrote:
> It would be convenient if someone can give me any leads to the first error.

https://github.com/sugarlabs/finance-activity/blob/master/filtertoolitem.py#L28

It looks to be a debugging tool left behind; people use `logging.error` in these situations because it is simpler than changing the debug level.
