### ISSUE TITLE
Update list after changing time period

### ISSUE THREAD

**Issue by pro-panda** [sugarlabs/finance-activity#18]
Suggestion from @TreeBaron in [sugar/#762](https://github.com/sugarlabs/sugar/issues/762),

> Finance Application - When selecting a period of forever in the finance application, the list is not updated until a new credit is added. I suggest the list be updated immediately upon selection.

**Comment by nswarup14** [comment]
@pro-panda 
Could you give more details on the issue?
I believe its working fine as it stands.
Thanks

**Comment by Hrishi1999** [comment]
Can not understand the issue. I tested and it seems to work fine. Need more details maybe?

**Comment by quozl** [comment]
Good, thanks, it might have been fixed already.  There have been changes.  Please test the v13 tag rather than HEAD.  Also share your test method, just in case it does not match what others are testing.

**Comment by pro-panda** [comment]
@nswarup14 would you like to take it up for testing ?

**Comment by quozl** [comment]
@TreeBaron, I've tested as of the current master branch and this problem has been fixed.
