### ISSUE TITLE
Cherry pick Debian files?

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/finance-activity#4]
I think it would be good to cherrypick https://github.com/tchx84/sugar-finance-activity/commit/3c565ad2bc5a01742dc519db9574dac522e6a1b4 here, so that @tchx84 's repo can be remade as a fork of this one :)

**Comment by godiard** [comment]
I would accept pull requests. But the repo is now in sugarlabs domain, then others can work on this too.

**Comment by quozl** [comment]
Don't think we want these Debian packaging files added to the upstream source, so closing.
